### ISSUE TITLE
关于多用户类型的问题

### ISSUE THREAD

**Issue by jt-wang** [dsdshcym/course-pick#3]
您好:

我在用 django 做一个lab面试预约系统，但是关于多用户类型的问题一直没有解决。搜了很长时间，终于找到了您的项目。非常感谢！

有几个小问题：

``` python
class Assistant(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=50)
    id = models.CharField(max_length=30, primary_key=True)
    user_type = 'assistant'

    def __str__(self):
        return self.name
```

如果像这样设置的话，整个验证系统仍然采用系统自带的User 对吧？我看到您在 https://www.v2ex.com/t/187480 提到 考虑过 用 groups 来实现。请问 Group 是如何使用呢...? （实在没有找到明确的文档）

如果不用 group，则您是如何实现的呢？

我看到在 https://github.com/dsdshcym/course-pick/blob/master/course_pick/views.py 里，
您使用:

``` python
    user = request.user
    if user.is_authenticated():
        try:
            if user.student:
                return redirect('/courses/student/')
        except:
            pass
```

请问 user.student 是 怎么来的呀？

您的回答会对我非常有帮助，谢谢~

**Comment by dsdshcym** [comment]
1. 对，这样设置是用的自带的 User
2. Group 我也没找到相关的文档，最后放弃了用 Group 实现。改用每次注册时单独分配权限，见 https://github.com/dsdshcym/course-pick/blob/master/accounts%2Fviews.py#L28-L39
3. user.student 是因为 Student 和 User 是 OneToOneField 。你的例子中也可以用 user.assistant 来调用。具体请看 OneToOneField 的文档。

**Comment by jt-wang** [comment]
谢谢！通过这篇文章http://haoluobo.com/trac/wiki/Django， 我找到了两个库，[django-userna](https://github.com/bread-and-pepper/django-userena/)，这是用户系统。
[django-guardian](https://github.com/django-guardian/django-guardian)，这是对象粒度的权限管理。前者基于后者，我想也许可以解决多用户类型的问题。

**Comment by jt-wang** [comment]
ps: 我看了你的博客发现...我们似乎是校友（你是学长）？:)

**Comment by dsdshcym** [comment]
是的呀，我是 13 计科的

**Comment by jt-wang** [comment]
我是转降到软工来了 :)

**Comment by dsdshcym** [comment]
13CS -> 14SE?

**Comment by jt-wang** [comment]
13英语到14软工

**Comment by dsdshcym** [comment]
先膜为敬

**Comment by jt-wang** [comment]
不黑不黑哈哈，我之前就听同学提过你，他是你高中学弟，说你给他们讲过题的

**Comment by dsdshcym** [comment]
很惭愧，做了一点微小的工作
